---
format: html
title: Studie zu einem 4-Phasen-Unterrichtsmodell
subtitle: Informationen zur Studienteilnahme
---


# Herzlich Willkommen

Sie kennen PADUA und AVIVA?

* **Ja?** <br> $\Longrightarrow$ helfen Sie mit ein neues Modell zu testen!
* **Nein?** <br> $\Longrightarrow$ lernen Sie ein Phasenmodell selbst kennen! 

Im Rahmen meiner Doktorarbeit bei [Prof. Dr. Christian Spannagel](https://www.youtube.com/@pharithmetik) erproben wir ein neuartiges 4-Phasen-Unterrichtsmodell an Hochschulen und wir suchen Studierende. **Machen Sie mit!**

Sie erhalten zwei Lektionen zu einem schulbezogenen Thema, welches Sie sehr wahrscheinlich noch nicht kennen.

:::mittig
[Mitmachen (PHBern)](https://forms.office.com/e/pm6KdeELwN){.knopf} [Mitmachen (Andere)](https://forms.office.com/Pages/ResponsePage.aspx?id=zwAKJW1LckaxbMo0bk4R5VfPrF0Zps1KgKhjsB14s1xUNUpZWTI2MTY0OUhXRjc1Rk40QUxRNlhBRy4u){.knopf}
:::

## Sie erhalten:

* Selbstgebackene Kekse vor Ort (mmmhh Cookies 🍪🍪🍪 ). 
* Möglichkeit einen von mehreren **Gutscheinen im Wert von 200 Chf** zu gewinnen **oder** als FEE Praktikum für PHBern Studienplan 13. 
* Einen professionell aufgearbeiteten Kurs nach dem 4-Phasenmodell.
* Persönliche Erfahrung mit einem Unterrichtsmodell für Ihren späteren Unterricht.
* Möglichkeit für persönliche Beratung zum Phasenmodell oder der Durchführung wissenschaftlicher Experimente nach dem Experiment. Eine super Vorbereitung für die Masterarbeit!


## Ihr Aufwand:
* Zweimal 50 Minuten Zeit (Daten stehen in der Umfrage).
* Zusätzliche Vorbereitungszeit zu Hause von 60 Minuten.

## Wann?

* Dienstags, 08.04.2025 und 15.04.2025 - 16:15 - 17:15
* Mittwochs, 23.04.2025 und 30.04.2025 - 10:15 - 11:15
* Dienstags, 29.04.2025 und 06.05.2025 - 13:00 - 14:00
* Mittwochs, 30.04.2025 und 07.05.2025 - 16:15 - 17:15
* Donnerstags, 01.05.2025 und 08.05.2025 - 16:15 - 17:15 

## Wo?

An der PHBern, Fabrikstrasse 8. Die genauen Räume erhalten Sie per Mail sobald die Zuteilungen gemacht sind.


## Wer kann mitmachen?

Alle eingeschriebene Personen der PHBern können mitmachen. Die Lektion wird zwar im Kontext der Mathematik stattfinden, sie wendet sich jedoch gleichermassen an Studierende aller A-Fächer und aller Studiengänge!

## Wer sieht meine Daten?

Alle Daten der Studie sind **anonymisiert**. Sie verwenden ein Codewort, welches nur Sie kennen. Es werden keine personenbezogene Daten gesammelt, welche Sie identifizieren könnten.


## Was passiert mit den anonymen Daten?

Die Daten werden ausgewertet um den Nutzen des Phasenmodells zu analysieren. Die Auswertung wird später in einem Paper (Artikel eines wissenschaftlichen Journals) publiziert.

## Kann ich meine Daten dennoch löschen lassen?

Ja! Sie erstellen ein Codewort, welches nur Sie kennen. Es hilft die Daten des ersten Tagen mit denen des zweiten Tages zu verbinden. Sie können bis 3 Wochen nach dem Experiment durch Nennen des Codewortes Ihre Daten löschen lassen.