---
format: html
title: Kompetenzorientierung
subtitle: Grundlagen der Beurteilung

authors:
  - name: Aline Löw
    affiliations:
      - ref: phbern
  - name: Daniel Ingrisani
    degrees: Dr.
    affiliations:
      - ref: phbern
  - name: Irene Althaus
    affiliations:
      - ref: phbern
citation: 
  author:
    - Aline Löw
    - Daniel Ingrisani
    - Irene Althaus
copyright: Dieser Kurs  basiert auf einer Lerngelegenheit von Aline Löw, Daniel Ingrisani und Irene Althaus. Diese haben die notwendigen Materialien freundlicherweise unter eine CC BY-SA 4.0 Lizenz gestellt.
abstract: >
  In diesem Lernmodul geht es um Kompetenzorientierung, kompetenzorientierter Unterricht und kompetenzorientierte Beurteilung. Der Begriff der Kompetenz und der Kompetenzraster ist spätestens seit der Einführung des LP21 in aller Munde, also sollten wir wissen, worum es sich dabei handelt.
---

::: callout-note
## Ziele des Lernmoduls

Die Studierenden ...
* erarbeiten sich vom Kompetenzbegriff ausgehend ein Verständnis der Kompetenzorientierung.
* entwickeln Vorstellungen darüber, welche Merkmale einen kompetenzorientierten Unterricht ausmachen.
* kennen wichtigte Komponenten, die für die Umsetzung einer kompetenzorientierten Beurteilung zentral sind.

:::

Davon ausgehend werden wir das Thema «Kompetenzorientierung» also in folgende vier Kapitel unterteilen.

1. Problemstellung
2. Begriffsklärung → Was ist Kompetenzorientierung?
3. Kompetenzorientierter Unterricht
4. Kompetenzorientierte Beurteilung

Als gleichsam übergeordnetes Ziel geht es auch darum, das Verständnis für den neuen Lehrplan 21 zu verbessern. Zumindest sollten Sie nachvollziehen können, weshalb die Kompetenzen im neuen Lehrplan so aufgebaut und dargestellt sind.

Da das Thema Kompetenzorientierung im Grunde nicht mehr neu ist, kann es gut sein, dass Sie sich bereits intensiv mit der Thematik beschäftigt haben. Scheuen Sie sich deshalb nicht, Ausführungen in den Slidecasts zu überspringen, wenn Sie diese als Wiederholung empfinden oder Sie in Ihren Augen keine neuen Sichtweisen bieten.

Arbeiten Sie das Lernmodul Schritt für Schritt durch.

Sollten Sie Fragen zum Thema haben, das Bedürfnis verspüren bestimmte Aspekte zu diskutieren oder wissen Sie nicht, wie Sie die behandelten Inhalte in Ihrem Beurteilungskonzept berücksichtigen sollen, dann ist es wichtig, dass Sie Ihre Anliegen an den dafür vorgesehenen Austauschterminen einbringen.

# 1 Problemstellung
Bevor wir uns mit der Kompetenzorientierung ansich beschäftigen, sollten wir uns fragen, worin denn das Problem für Lehrpersonen mit diesem Thema besteht und was die Einführung des Lehrplan 21 mit seiner ausgeprägten kompetenzorientierten Ausprägung bei den Lehrpersonen ausgelöst hat.

:::{#fig-problemstellung}
<iframe src="https://tube.switch.ch/embed/vcZBrB67qY?title=hide" frameborder="0" allow="fullscreen"></iframe> 

Screencast - Problemstellung ([Slides](screencast_slides/LM_07_01_Kompetenzorientierung_Problemstellung.pdf))
:::

# 2 Begriffsklärung
Ausgehend von der Definition und von einem neuen Verständnis des Begriffs «Kompetenz», beschäftigt sich dieses Kapitel mit der Ausrichtung der Kompetenzorientierung im neuen Lehrplan 21. Wir fragen uns, wie die Kompetenzformulierungen im Lehrplan 21 entstanden und wie diese zu verstehen sind. Um diese Fragen beantworten zu können, müssen wir uns mit dem Kompetenzbegriff, der dem Lehrplan zugrunde liegt auseinandersetzen und uns auch damit beschäftigen, wie die Entwicklung der Kompetenzformulierungen im Lehrplan stattgefunden hat.


:::{#fig-begriff}
<iframe src="https://tube.switch.ch/embed/3WFJH1zBMK?title=hide" frameborder="0" allow="fullscreen"></iframe>

Screencast - Begriffsklärung ([Slides](screencast_slides/LM_07_02_Kompetenzorientierung_Begriffsklaerung.pdf))
:::

# 3 Kompetenzorientierter Unterricht
In Anlehnung an Rudolf Künzli (2013, S. 3) können wir davon ausgehen, dass jede Einführung eines neuen Lehrplans immer auch mit einem neuen, innotativen Unterrichtsverständnis bzw. mit einer neuen, innovativen Unterrichtspraxis in Verbindung steht.
 
> «Wo neue Lehrpläne Änderungen bringen, und die sind in aller Regel eng begrenzt, wurden diese meistens bereits an einzelnen Schulen schon praktiziert. Was so Eingang in die neuen Lehrpläne findet und bislang ausserhalb des von den alten Lehrplänen gesetzten Rahmens praktiziert wurde, wird so gleichsam nachträglich anerkannt und offiziell. Offizialisierung von innovativen Praxisbeispielen ist denn auch die hauptsächliche Wirkung von Lehrplänen. Der Offizialisierung steht eine mehr oder weniger deutliche Delegitimierung überkommener Praxis gegenüber.» (Künzli 2013, S. 3).
 
Im neuen Lehrplan 21 ist diese Offizialisierung und Legitimierung innovativer Unterrichtspraxis die «Kompetenzorientierung» bzw. der «kompetenzorientierte Unterricht». Wenn allerdings «Neues» und Innovatives legitimiert wird, dann ist damit immer auch eine Delegitimierung von «Altem» und Herkömmlichem verbunden. Wir müssen uns also die Frage stellen, was denn kompetenzorientierter Unterricht nun genau ist und inwiefern damit tatsächlich etwas Neues und Innovatives auf uns zukommt.

:::{#fig-kompetenzorientiert}
<iframe src="https://tube.switch.ch/embed/1MHBWhla3N?title=hide" frameborder="0" allow="fullscreen"></iframe>

Screencast - Kompetenzorientierter Unterricht ([Slides](screencast_slides/LM_07_03_Kompetenzorientierung_Kompetenzorientierter_Unterricht.pdf))
:::

# 4 Kompetenzorientierte Beurteilung
Erst wenn wir wissen, was Kompetenzorientierung (im Lehrplan 21) ist (siehe Kapitel 2 «Begriffsklärung») und wie davon ausgehend kompetenzorientierter Unterricht zu verstehen ist (siehe Kapitel 3 «Kompetenzorientierter Unterricht»), können wir uns schliesslich mit der Frage beschäftigen, wie denn eine kompetenzorientierte Beurteilung aussehen muss.

Hier beantworten diese Frage noch sehr allgemein. In anderen Lernmodulen (z.B. Förderorientierung, Gesamturteil) und auch in den Austauschveranstaltungen gehen wir etwas konkreter auch auf Beispiele ein.

:::{#fig-beurteilung}
<iframe src="https://tube.switch.ch/embed/dLWAAvKWcV?title=hide" frameborder="0" allow="fullscreen"></iframe>

Screencast - Kompetenzorientierte Beurteilung ([Slides](screencast_slides/LM_07_04_Kompetenzorientierung_Kompetenzorientierte_Beurteilung.pdf))
:::

# Verarbeitungsauftrag

Sie haben unten Zugriff auf eine [Reihe von Kompetenzrastern](https://phbern365.sharepoint.com/:f:/r/sites/IS1.Z.Studienplanentwicklung2022/Freigegebene%20Dokumente/General/BA%20-%20Beurteilung%20(formativ%20und%20summativ)/Lerngelegenheiten/Grundlagen%20der%20Beurteilung%20SOL%20-%20Conrardy/LM_07?csf=1&web=1&e=IdbDT7), die am Institut Beatenberg, namentlich eine Privatschule, wo die SuS schon seit Jahren mit Kompetenzrastern kompetenzorientiert unterrichtet werden.

Studieren Sie mindestens zwei davon etwas intensiver und analysieren Sie diese vor dem Hintergrund dessen, was Sie sich anhand des Inputs erarbeitet haben. Folgende Fragen können Sie bei der Analyse leiten und unterstützen.

* Wie werden die Kompetenzen formuliert?
* Wie werden die Kompetenzniveaus aufeinander aufgebaut? → Stichwort «Kumulatives Lernen»
* Können Aufgaben tatsächlich Indikatoren für die hier zugrunde liegenden Kompetenzen sein?
* Wie muss eine Beurteilung aussehen, die sich auf solche oder ähnliche Kompetenzraster bezieht?

Machen Sie sich Notizen zuhanden Ihres Beurteilungskonzepts.
